theme: jekyll-theme-minimal
title: Matteo Ciocca's homepage

# show/remove downloads bottoms
logo: /career/photos/me_web.jpg

# show/remove downloads bottoms
show_downloads: false

# description: This is me (with my pain au chocolat hat)

# https://github.com/pages-themes/minimal?tab=readme-ov-file#usage

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
